#!/bin/bash

loginManager () {

  LG="ly"

  cmd=(dialog --keep-tite --no-collapse --cr-wrap --backtitle "${title}" --title "-| Login Manager |-" --column-separator "|" --no-tags --ok-label '< Seleccionar >' --nocancel --menu "\nElige una opción\n " 12 50 12)

  options=(1 "ly"
           2 "lightdm"
           3 "sddm")

  choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

  for choice in $choices
    do
      case $choice in
        1)
          LG="ly"
          ;;
        2)
          LG="lightdm"
          ;;
        3)
          LG="sddm"
          ;;
      esac
    done
}


installLoginManager () {

  case $LG in 

    "ly")
      echo "" 
      echo "Se esta instalando LY:" 
      echo "" 
      arch-chroot /mnt /bin/bash -c "pacman -Syu ly --noconfirm"
      arch-chroot /mnt /bin/bash -c "systemctl enable ly"
      ;;

    "lightdm")
      echo "" 
      echo "Se esta instalando LightDM:" 
      echo "" 

      arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm --noeditmenu --noconfirm --needed"
      arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
      arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
      arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S light-locker --noeditmenu --noconfirm --needed"
      arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"
      ;;

    "sddm")
      echo "" 
      echo "Se esta instalando SDDM:" 
      echo "" 

      arch-chroot /mnt /bin/bash -c "pacman -S sddm --needed --noconfirm"
      arch-chroot /mnt /bin/bash -c "sudo systemctl enable sddm"
      arch-chroot /mnt /bin/bash -c "sudo -u $username paru -Sy sddm-sugar-dark --noconfirm --needed"
      arch-chroot /mnt /bin/bash -c "sudo cp /usr/lib/sddm/sddm.conf.d/default.conf /usr/lib/sddm/sddm.conf.d/default.conf.backup && sudo sed -i 's/^Current=*.*/Current=sugar-dark/g' /usr/lib/sddm/sddm.conf.d/default.conf"
      ;;
  esac
}

