#!/bin/bash

shellsystem () {

  shell=""

  cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --title "${title_shell}" \
  --no-tags --ok-label "${btn_confirm}" --nocancel --menu "${msg_shell}" 15 52 15)
  options=(1 " zsh  "   
           2 " bash "
           3 " fish "
           4 " dash "
           5 " mksh "
           6 " tcsh ")
  choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
  clear
  for choice in $choices
    do
      case $choice in

        1)
          shell="zsh"
          sectionshell=1
          ;;

        2)
          shell="bash"
          sectionshell=1
          ;;

        3)
          shell="fish"
          sectionshell=1
          ;;

        4)
          shell="dash"
          sectionshell=1
          ;;

        5)
          shell="mksh"
          sectionshell=1
          ;;

        6)
          shell="tcsh"
          sectionshell=1
          ;;
                                                
      esac
    done
}

installshell () {

  case $shell in

    zsh)
      arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S zsh --noeditmenu --noconfirm --needed"
      ;;

    bash)
      arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S bash --noeditmenu --noconfirm --needed"
      ;;

    dash)
      arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dash --noeditmenu --noconfirm --needed"
      ;;

    fish)
      arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S fish --noeditmenu --noconfirm --needed"
      ;;

    mksh)
      arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mksh --noeditmenu --noconfirm --needed"
      ;;

    tcsh)
      arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S tcsh --noeditmenu --noconfirm --needed"
      ;;

  esac

  echo ""

  arch-chroot /mnt /bin/bash -c "chsh -s /bin/$shell"
  arch-chroot /mnt /bin/bash -c "chsh -s /usr/bin/$shell $username"
  arch-chroot /mnt /bin/bash -c "chsh -s /bin/$shell $username"

  cp .dialogrc /mnt/root
  chmod +x /mnt/root/.dialogrc
  cp .dialogrc /mnt/home/$username/.dialogrc
  chmod +x /mnt/home/$username/.dialogrc

  mkdir /mnt/etc/pacman.d/hooks/
  cp mirrorupgrade.hook /mnt/etc/pacman.d/hooks/mirrorupgrade.hook 
  chmod +x /mnt/etc/pacman.d/hooks/mirrorupgrade.hook
  # Install powerlevel10k
  mkdir -p /mnt/root/.config
  mkdir -p /mnt/home/$username/.config
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git 
  cp -r powerlevel10k /mnt/home/$username/.config/powerlevel10k
  cp -r powerlevel10k /mnt/root/.config/powerlevel10k
  rm -Rf powerlevel10k
  # Configure dotfiles
  git clone https://github.com/JAri07/dotfiles.git
  mkdir -p /mnt/home/$username/.local/fonts
  cp -r dotfiles/user/.local/fonts/* /mnt/home/$username/.local/fonts
  cp dotfiles/user/.zshrc /mnt/home/$username/.zshrc
  cp dotfiles/user/.p10k.zsh /mnt/home/$username/.p10k.zsh
  cp dotfiles/root/.zshrc /mnt/root/.zshrc
  cp dotfiles/root/.p10k.zsh /mnt/root/.p10k.zsh
  rm -Rf dotfiles
  arch-chroot /mnt /bin/bash -c "chown -hR $username:users /home/$username/.zshrc"
  arch-chroot /mnt /bin/bash -c "chown -hR $username:users /home/$username/.p10k.zsh"
}
